<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48201" started-at="2017-09-18T14:22:14Z" finished-at="2017-09-18T14:23:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="48201" started-at="2017-09-18T14:22:14Z" finished-at="2017-09-18T14:23:02Z">
      <class name="com.transavia.Test_Id_4">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.transavia.Test_Id_4@a74868d]" name="beforeClass" is-config="true" duration-ms="28816" started-at="2017-09-18T16:22:14Z" finished-at="2017-09-18T16:22:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TestId4()[pri:0, instance:com.transavia.Test_Id_4@a74868d]" name="TestId4" duration-ms="19342" started-at="2017-09-18T16:22:43Z" finished-at="2017-09-18T16:23:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Price is wrong! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Price is wrong! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.transavia.Test_Id_4.TestId4(Test_Id_4.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestId4 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.transavia.Test_Id_4@a74868d]" name="afterClass" is-config="true" duration-ms="4" started-at="2017-09-18T16:23:02Z" finished-at="2017-09-18T16:23:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.transavia.Test_Id_4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
